const Route = use('Route')

Route.get('/', 'UserController.index').prefix('users')
Route.get('/:id([0-9]+)', 'UserController.find').prefix('user')
Route.get('/getprofileimg/:id([0-9]+)', 'UserController.getprofileImg').prefix('user')
Route.get('/:userId/postits', 'UserController.getPostits').prefix('user')
Route.post('/', 'UserController.create').prefix('user').formats(['json']).validator('user/CreateUser')
Route.post('/auth', 'UserController.login').prefix('user').formats(['json']).validator('user/AuthUser')//.middleware(['auth'])
Route.get('/logout', 'UserController.logout').prefix('user')
Route.put('/:id', 'UserController.update').prefix('user').formats(['json']).validator('user/UpdateUser')
Route.post('/uploadimg', 'UserController.uploadImg').prefix('user')
Route.delete('/:id', 'UserController.delete').prefix('user')